### ISSUE TITLE
Need for clarity in the README for newcomers like me

### ISSUE THREAD

**Issue by Lucifer516-sudoer** [Shyamnath-Sankar/Embedding-Using-Rag#1]
@Shyamnath-Sankar , would you mind adding little bit more descriptive, readme, or anything that will be helpful to understand these scripts?

**Comment by Shyamnath-Sankar** [comment]
I will add in organisation this is under development

**Comment by Lucifer516-sudoer** [comment]
> I will add in organisation this is under development

ok, got it

**Comment by Lucifer516-sudoer** [comment]
@Shyamnath-Sankar , I am forking your repo da, and I wish to add this repo to our organization, after modifying the code.

**Comment by Shyamnath-Sankar** [comment]
Ok cool
